String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>physics people!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "physics images by us all!
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-physics #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Sam',
    '%4'                    : 'Jeremiah',
    '%8'                    : 'Ryan',
    '%16'                   : 'Meerab',
    '%32'                   : 'Tamara',
    '%64'                   : 'gay brothers',
    '%128'                  : 'Jayden',
    '%256'                  : 'tamara',
    '%512'                  : 'jayovO',
    '%1024'                 : 'james',
    '%2048'                 : 'Elijah',
    '%4096'                 : 'Colton',
    '%8192'                 : 'zevian',
    '%p0'                   : 'Sam',
    '%p4'                   : 'Jeremiah',
    '%p8'                   : 'Ryan',
    '%p16'                  : 'Meerab',
    '%p32'                  : 'Tamara',
    '%p64'                  : 'gay brothers',
    '%p128'                 : 'Jayden',
    '%p256'                 : 'tamara',
    '%p512'                 : 'jayovO',
    '%p1024'                : 'james',
    '%p2048'                : 'Elijah',
    '%p4096'                : 'Colton',
    '%p8192'                : 'zevian'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Physics people!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "mit images by me!",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-physics #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Sam',
    '%4'                    : 'Jeremiah',
    '%8'                    : 'Ryan',
    '%16'                   : 'Meerab',
    '%32'                   : 'Tamara',
    '%64'                   : 'gay brothers',
    '%128'                  : 'Jayden',
    '%256'                  : 'tamara',
    '%512'                  : 'jayovO',
    '%1024'                 : 'james',
    '%2048'                 : 'Elijah',
    '%4096'                 : 'Colton',
    '%8192'                 : 'zevian',
    '%p0'                   : 'Sam',
    '%p4'                   : 'Jeremiah',
    '%p8'                   : 'Ryan',
    '%p16'                  : 'Meerab',
    '%p32'                  : 'Tamara',
    '%p64'                  : 'gay brothers',
    '%p128'                 : 'Jayden',
    '%p256'                 : 'tamara',
    '%p512'                 : 'jayovO',
    '%p1024'                : 'james',
    '%p2048'                : 'Elijah',
    '%p4096'                : 'Colton',
    '%p8192'                : 'zevian'
  }

});
